/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthedBrandsRouteImport } from './routes/_authed/brands'
import { Route as AuthedCampaignsRouteImport } from './routes/_authed/campaigns'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedCampaignsIdRouteImport } from './routes/_authed/campaigns.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PlayBrandSlugCampaignSlugRouteImport } from './routes/play.$brandSlug.$campaignSlug'
import { Route as ApiPlayBrandSlugCampaignSlugRouteImport } from './routes/api/play/$brandSlug.$campaignSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedBrandsRoute = AuthedBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCampaignsRoute = AuthedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCampaignsIdRoute = AuthedCampaignsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedCampaignsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayBrandSlugCampaignSlugRoute =
  PlayBrandSlugCampaignSlugRouteImport.update({
    id: '/play/$brandSlug/$campaignSlug',
    path: '/play/$brandSlug/$campaignSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPlayBrandSlugCampaignSlugRoute =
  ApiPlayBrandSlugCampaignSlugRouteImport.update({
    id: '/api/play/$brandSlug/$campaignSlug',
    path: '/api/play/$brandSlug/$campaignSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/brands': typeof AuthedBrandsRoute
  '/campaigns': typeof AuthedCampaignsRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/campaigns/$id': typeof AuthedCampaignsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/play/$brandSlug/$campaignSlug': typeof PlayBrandSlugCampaignSlugRoute
  '/api/play/$brandSlug/$campaignSlug': typeof ApiPlayBrandSlugCampaignSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/brands': typeof AuthedBrandsRoute
  '/campaigns': typeof AuthedCampaignsRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/campaigns/$id': typeof AuthedCampaignsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/play/$brandSlug/$campaignSlug': typeof PlayBrandSlugCampaignSlugRoute
  '/api/play/$brandSlug/$campaignSlug': typeof ApiPlayBrandSlugCampaignSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authed/brands': typeof AuthedBrandsRoute
  '/_authed/campaigns': typeof AuthedCampaignsRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/campaigns/$id': typeof AuthedCampaignsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/play/$brandSlug/$campaignSlug': typeof PlayBrandSlugCampaignSlugRoute
  '/api/play/$brandSlug/$campaignSlug': typeof ApiPlayBrandSlugCampaignSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/brands'
    | '/campaigns'
    | '/dashboard'
    | '/campaigns/$id'
    | '/api/auth/$'
    | '/play/$brandSlug/$campaignSlug'
    | '/api/play/$brandSlug/$campaignSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/brands'
    | '/campaigns'
    | '/dashboard'
    | '/campaigns/$id'
    | '/api/auth/$'
    | '/play/$brandSlug/$campaignSlug'
    | '/api/play/$brandSlug/$campaignSlug'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/register'
    | '/_authed/brands'
    | '/_authed/campaigns'
    | '/_authed/dashboard'
    | '/_authed/campaigns/$id'
    | '/api/auth/$'
    | '/play/$brandSlug/$campaignSlug'
    | '/api/play/$brandSlug/$campaignSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  PlayBrandSlugCampaignSlugRoute: typeof PlayBrandSlugCampaignSlugRoute
  ApiPlayBrandSlugCampaignSlugRoute: typeof ApiPlayBrandSlugCampaignSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/brands': {
      id: '/_authed/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof AuthedBrandsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/campaigns': {
      id: '/_authed/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthedCampaignsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/campaigns/$id': {
      id: '/_authed/campaigns/$id'
      path: '/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AuthedCampaignsIdRouteImport
      parentRoute: typeof AuthedCampaignsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$brandSlug/$campaignSlug': {
      id: '/play/$brandSlug/$campaignSlug'
      path: '/play/$brandSlug/$campaignSlug'
      fullPath: '/play/$brandSlug/$campaignSlug'
      preLoaderRoute: typeof PlayBrandSlugCampaignSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/play/$brandSlug/$campaignSlug': {
      id: '/api/play/$brandSlug/$campaignSlug'
      path: '/api/play/$brandSlug/$campaignSlug'
      fullPath: '/api/play/$brandSlug/$campaignSlug'
      preLoaderRoute: typeof ApiPlayBrandSlugCampaignSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedCampaignsRouteChildren {
  AuthedCampaignsIdRoute: typeof AuthedCampaignsIdRoute
}

const AuthedCampaignsRouteChildren: AuthedCampaignsRouteChildren = {
  AuthedCampaignsIdRoute: AuthedCampaignsIdRoute,
}

const AuthedCampaignsRouteWithChildren = AuthedCampaignsRoute._addFileChildren(
  AuthedCampaignsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedBrandsRoute: typeof AuthedBrandsRoute
  AuthedCampaignsRoute: typeof AuthedCampaignsRouteWithChildren
  AuthedDashboardRoute: typeof AuthedDashboardRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedBrandsRoute: AuthedBrandsRoute,
  AuthedCampaignsRoute: AuthedCampaignsRouteWithChildren,
  AuthedDashboardRoute: AuthedDashboardRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  PlayBrandSlugCampaignSlugRoute: PlayBrandSlugCampaignSlugRoute,
  ApiPlayBrandSlugCampaignSlugRoute: ApiPlayBrandSlugCampaignSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
